version: '3.8'

services:
  app:
    image: demo
    ports:
      - 8080:8080
  zap:
    image: owasp/zap2docker-stable
    volumes:
    - ./zap:/zap/wrk/:rw
    command: zap-api-scan.py -t http://app:8080/swagger/demo-0.0.yml -f openapi -r testreport.html
    depends_on:
      - app
