version: '3.8'

services:
  app:
    image: demo
    ports:
      - 8080:8080
  zap:
    image: owasp/zap2docker-stable
    volumes:
    - ./zap:/zap/wrk/:rw
    command: >
      zap-api-scan.py
      -t http://app:8080/swagger/demo-0.0.yml
      -f openapi
      -r testreport.html
      -c zap.confg
      -z "-addoninstall sqliplugin
      -config replacer.full_list\\(0\\).description=auth1
      -config replacer.full_list\\(0\\).enabled=true
      -config replacer.full_list\\(0\\).matchtype=REQ_HEADER
      -config replacer.full_list\\(0\\).matchstr=Authorization
      -config replacer.full_list\\(0\\).regex=false
      -config replacer.full_list\\(0\\).replacement='Bearer 123'"
    user: $USER
    depends_on:
      - app
