name: owasp api scan

on: workflow_dispatch

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run app
        run: |
          ./gradlew buildLayers
          ./gradlew dockerBuild
          docker-compose up -d

      - name: OWASP ZAP SCAN
        run: |
          TARGET_URL="http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):8080/swagger/demo-0.0.yml "
          docker run --rm \
               --user root \
               -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-api-scan.py \
               -t $TARGET_URL \
               -f openapi \
               -r testreport.html \
               -z "-addoninstall sqliplugin  \
               -config replacer.full_list\\(0\\).description=auth1 \
               -config replacer.full_list\\(0\\).enabled=true \
               -config replacer.full_list\\(0\\).matchtype=REQ_HEADER \
               -config replacer.full_list\\(0\\).matchstr=Authorization \
               -config replacer.full_list\\(0\\).regex=false \
               -config replacer.full_list\\(0\\).replacement='Bearer 123'"

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: my-artifact
          path: testreport.html

      - name: Stop app
        run: |
          docker-compose down

